# Derivadas superiores

Hasta ahora hemos visto que, usando diferenciación automática, podemos calcular la derivada de funciones de una variable esencialmente con un error del orden del epsilon de la máquina.

La pregunta que abordaremos ahora, es cómo hacer para calcular la segunda derivada, y derivadas de orden superior.

Una posibilidad, específica para el caso de la segunda derivada, es proceder como en el caso anterior, es decir, definir una *terna ordenada* donde la primer componente es el valor de la función en $x_0$, i.e., $f(x_0)$, el de la segunda es el valor de la primer derivada $f'(x_0)$, y la tercer componente tiene el valor de la segunda derivada, $f^{(2)}(x_0) = f''(x_0)$. 


Con esta definición, las operaciones aritméticas vienen dadas por:

\begin{eqnarray}
\vec{u} + \vec{v} & = & (u + v, \quad u'+ v', \quad u''+v''),\\
\vec{u} - \vec{v} & = & (u - v, \quad u'- v', \quad u''-v''),\\
\vec{u} \times \vec{v} & = & (u v, \quad u v' + u' v, \quad u v'' + 2 u' v' + u'' v),\\
\frac{\vec{u}}{\vec{v}} & = & \Big( \frac{u}{v}, \quad \frac{u'-( u/v) v'}{v}, \quad 
\frac{u'' - 2 (u/v)' v' - (u/v)v'' }{v}\Big).\\
\end{eqnarray}

Claramente, este proceso es muy ineficiente para derivadas de orden aún más alto, dado que las expresiones se complican y es fácil cometer errores.

# Series de Taylor

El punto importante a recordar, es que las derivadas de orden superior de una función $f(x)$ en un punto $x_0$ están contenidas en el desarrollo de Taylor de la función entorno a ese punto. La suposición importante en esto es que $f(x)$ es suficientemente suave; por simplicidad supondremos que $f(x)$ es ${\cal C}^\infty$ y que estamos suficientemente cerca del punto $x_0$, i.e., $|x-x_0|\ll 1$. 


La serie de Taylor de $f(x)$ viene dada por

\begin{eqnarray}
f(x) & = & f(x_0) + f^{(1)}(x_0) (x-x_0) + \frac{f^{(2)}(x_0)}{2!} (x-x_0)^2 + \dots + \frac{f^{(k)}(x_0)}{k!} (x-x_0)^k + \dots,\\
& = & f_{[0]} + f_{[1]} (x-x_0) + f_{[2]} (x-x_0)^2 + \dots + f_{[k]} (x-x_0)^k + \dots,\\
\end{eqnarray}

donde los coeficientes *normalizados* de Taylor $f_{[k]}$ que aparecen en la segunda línea de la ecuación anterior se definen como

\begin{equation}
f_{[k]} = \frac{f^{(k)}(x_0)}{k!} = \frac{1}{k!}\frac{{\rm d}^k f}{{\rm d}x^k}(x_0).
\end{equation}



Vale la pena **enfatizar** que la expresión anterior es exacta en tanto que la serie **no** sea truncada. En el caso de que la serie truncada a orden k, el [teorema de Taylor](https://en.wikipedia.org/wiki/Taylor%27s_theorem) asegura que el residuo (error del truncamiento) se puede escribir como:

\begin{equation}
{\cal R_{k}} = \frac{f^{(k+1)}\,(\xi)}{(k+1)!} (x-x_0)^{k+1},
\end{equation}

donde $\xi$ es un punto que pertenece al interval $[x_0,x]$.


Si la serie es truncada, la aproximación es un polinomio de orden $k$ (grado máximo es $k$) en $x$. Dado que los polinomios en una variable están definidos por $k+1$ coeficientes, entonces pueden ser mapeados a vectores en $\mathbb{R}^{k+1}$. 

Las operaciones aritméticas, en este caso, vienen dadas por:

\begin{eqnarray}
(f+g)_{[k]} & = & f_{[k]} + g_{[k]} ,\\
(f-g)_{[k]} & = & f_{[k]} - g_{[k]} ,\\
(f \cdot g)_{[k]} & = & \sum_{i=0}^k f_{[i]} \,g_{[k-i]} \, ,\\
\Big(\frac{f}{g}\Big)_{[k]} & = & \frac{1}{g_{[0]}}
\Big( f_{[k]} - \sum_{i=0}^{k-1} \big(\frac{f}{g}\big)_{[i]} \, g_{[k-i]} \Big) . \\
\end{eqnarray}

### Ejercicio

Implementen una nueva estructura paramétrica (`type`) que defina el tipo `Taylor`, donde el parámetro debe ser un subtipo de `Number`. Definan métodos que implementen las operaciones aritméticas básicas (`+`, `-`, `*`, `/`) y la igualdad (`==`). Esto deberá ser incluido en un módulo.

Incluyan pruebas (en el archivo "runtests.jl") para cada uno de los métodos que implementen.

In [1]:
"""Definición de polinomios de Taylor, donde
...
"""
type Taylor{T<:Number}
    coef :: Array{T,1} # coeficiente normalizado de Taylor
end
Taylor(a) = Taylor(promote(a)...)

Taylor{T<:Number}

In [2]:
function paso2(f,g)
    nocero = 1
    orden = length(f)
    h = zeros(f)
    total = 0
    while g[nocero] == 0
        nocero += 1
    end
    h[1] = f[nocero]/g[nocero]
    for k in nocero+1:orden
        for i in 1:k-nocero
            if length(h) < i || length(g) < k-i+1
                continue
            else
                total += h[i]*g[k-i+1]
            end
        end
        h[k-nocero+1] = (f[k] - total)/g[nocero]
    end
    h
end

paso2 (generic function with 1 method)

In [3]:
function paso1(a,b)
    #if length(a) > length(b)
    #    c = zeros(a)
    #    orden = length(a)
    #else
    #    c = zeros(b)
    #    orden = length(b)
    #end
    order=length(a)+length(b)
    c = zeros(order)
    total = 0
    i = 0
    for k in 1:order
        for i in 1:k
            if i >length(a) || k-i+1 > length(b)
                continue
            else
                total += a[i]*b[k-i+1]
            end
        end
        c[k] = total
        total = 0
    end
    c
end

paso1 (generic function with 1 method)

In [4]:
function igualdad(a,b)
    orden = min([length(a),length(b)]...)
    i = 1
    while i <= orden
        if a[i] != b[i]
            return false
        end
        i+=1
    end
    return true
end

igualdad (generic function with 1 method)

In [5]:
import Base: +, -, *, /, ==

# Aqui se implementan los métodos necesarios para cada función

+(a::Taylor, b::Taylor) = Taylor(a.coef.+b.coef)
-(a::Taylor, b::Taylor) = Taylor(a.coef.-b.coef)
*(a::Taylor, b::Taylor) = Taylor(paso1(a.coef,b.coef))
/(a::Taylor, b::Taylor) = Taylor(paso2(a.coef,b.coef))
==(a::Taylor, b::Taylor) = igualdad(a.coef,b.coef)

== (generic function with 110 methods)

In [6]:
# Muestren que su código funciona con tests adecuados; para los detalles ver 
# http://julia.readthedocs.org/en/release-0.4/stdlib/test/
using Base.Test

@test Taylor([1,2,3])+Taylor([2,3,4]) == Taylor([3,5,7])
@test Taylor([1,2,3])-Taylor([2,3,4]) == Taylor([-1,-1,-1])
@test Taylor([0,0,1])/Taylor([0,1]) == Taylor([0,1,0])
@test Taylor([0,0,1,0])/Taylor([0,0,1]) == Taylor([1,0,0,0])
@test Taylor([0,1,1])*Taylor([0,1]) == Taylor([0,0,1,1])

# Funciones de polinomios

El siguiente punto, es cómo definir funciones de polinomios. 

Como veremos aquí, esto se basará en plantear una ecuación diferencial apropiada, cuya solución es, precisamente, la expresión que estamos buscando. Este punto es *importante*, y muestra que hay una conexión importante con la solución de ecuaciones diferenciales.

Como ejemplo consideraremos la función

\begin{equation}
E(x) = \exp\big(g(x)\big),
\end{equation}

donde 

\begin{equation}
g(x) = \sum_{k=0}^\infty g_{[k]} (x-x_0)^k
\end{equation}

está escrita como una serie de Taylor (¡exacta!) alrededor de $x_0$. 


El primer punto, es que escribiremos a $E(x)$ como una serie de Taylor alrededor de $x_0$, es decir,

\begin{equation}
E(x) = \sum_{k=0}^\infty E_{[k]} (x-x_0)^k.
\end{equation}

El objetivo es determinar $E_{[k]}$ para *toda* $k$.

Dado que $E(x)$ esun polinomio en $x$, su derivada viene dada por

\begin{equation}
\frac{{\rm d} E(x)}{{\rm d}x} = \sum_{k=1}^\infty k E_{[k]}\, (x-x_0)^{k-1} .
\end{equation}

Por otra parte, la derivada de $E(x)$ en términos de $g(x)$ está dada por

\begin{equation}
\frac{{\rm d} E(x)}{{\rm d}x} = \exp\big(g(x)\big) \frac{{\rm d} g(x)}{{\rm d}x} = E(x) \frac{{\rm d} g(x)}{{\rm d}x},
\end{equation}

donde del lado derecho aparece la derivada de $g(x)$. Ya que $g(x)$ *también* está escrita en forma polinomial, su derivada es

\begin{equation}
\frac{{\rm d} g(x)}{{\rm d}x} = \sum_{k=1}^\infty k g_{[k]}\, (x-x_0)^{k-1} .
\end{equation}


Tenemos, entonces, todo lo que requerimos para escribir el lado derecho de la ecuación diferencial y explotar la aritmética de polinomios. 

\begin{eqnarray}
E(x) \frac{{\rm d} g(x)}{{\rm d}x}& = & 
\Big[ \sum_{k=0}^\infty E_{[k]} (x-x_0)^k \Big]
\Big[ \sum_{j=1}^\infty j g_{[j]} (x-x_0)^{j-1}\Big] \\
 & = & \sum_{k=1}^\infty \Big[ \sum_{j=0}^k j g_{[j]} E_{[k-j]} \; \Big] (x-x_0)^{k-1} .\\
\end{eqnarray}

La segunda línea se obtiene reordenando los términos al fijar la potencia de $(x-x_0)$, esto es, $k+j$ se toma como un nuevo índice ($k$), y el nuevo índice $j$ describe el índice del producto de los polinomios. (La potencia se deja de la forma $k-1$ ya que el lado izquierdo de la ecuación aparece así.)

Igualando con el lado izquierdo de la ecuación diferencial, que sólo involucra a la derivada de $E(x)$, tenemos que se debe cumplir

\begin{equation}
E_{[k]} = \frac{1}{k} \sum_{j=0}^k j g_{[j]} \, E_{[k-j]} = 
\frac{1}{k} \sum_{j=0}^{k} (k-j) g_{[k-j]} \, E_{[j]}, \qquad k=1,2,\dots,
\end{equation}

incluyendo *la condición inicial*

\begin{equation}
E_{[0]} = \exp\big(g(x_0)\big).
\end{equation}

Estas relaciones *de recurrencia* permiten calcular $\exp\big(g(x)\big)$, para cualquier polinomio $g(x)$.

Para el caso concreto $g(x) = x$ alrededor de $x_0=0$, donde tenemos $g_{[j]} = \delta_{j,1}$, obtenemos

\begin{eqnarray}
E_{[0]} & = & 1,\\
E_{[k]} & = & \frac{1}{k} E_{[k-1]} = \frac{1}{k(k-1)} E_{[k-2]} = \dots = \frac{1}{k!} E_{[0]} = \frac{1}{k!}\ ,
\end{eqnarray}

que es el resultado bien conocido.

### Ejercicio

Obtengan las relaciones de recurrencia para las funciones $L(x) = \log\big(g(x)\big)$, $P_\alpha(x) = \big(g(x)\big)^\alpha$, $S(x) = \sin\big(g(x)\big)$, $C(x) = \cos\big(g(x)\big)$ usando el mismo procedimiento que arriba. Implementen métodos adecuados para estas funciones en el módulo, actuando sobre estructuras `Taylor` e incluyan pruebas.

$$
L_{[k+1]} = \Bigl[(k+1)g_{[k+1]}-\sum_{l=1}^{\infty}g_{[l]} L_{[k-l+1]}(k-l+1)\Bigr]/g_{[0]}(k+1),
$$
con $L_{[0]} = 0$.

Para el caso $g(x) = x$ alrededor de $x_0 = 1$, $g[j] = \delta_{j,0}+\delta_{j,1}$, tenemos

\begin{eqnarray}
L_{[1]} & = & 1,\\
L_{[k+1]} & = & -\frac{1}{k+1} L_{[k]} k = \frac{(-1)^2L_{[k-1]}k(k-1)}{(k+1)k} = \dots = (-1)^k \frac{1}{k+1}\ ,
\end{eqnarray}

que es el resultado de [wolfram](http://www.wolframalpha.com/input/?i=taylor+log%28x%29+x+%3D+1)

In [7]:
function log(g)
    L = zeros(g)
    L[2] = 1.
    total = 0
    for k in 3:length(g)
        total = 0
        for l in 2:k-1
            total += (k-l)*L[k-l+1]*g[l]
        end
        if k+1 <= length(g)
            L[k] = (k*g[k+1]-total)/(g[1]*(k-1))
        else
            L[k] = -total/(g[1]*(k-1))
        end
    end
    L
end

log (generic function with 1 method)

In [8]:
log([1//1,1//1,0])

3-element Array{Rational{Int64},1}:
  0//1
  1//1
 -1//2

Utilizamos la expresión
$$
\begin{eqnarray}
(P_{\alpha})_{[0]} & = & x_0^{\alpha},\\
(P_{\alpha})_{[k]} & = & \frac{1}{(k+1)g_{[0]}} \Bigl[\alpha\sum_{l=0}^k (k-l+1)P_{\alpha [l]}g_{[k-l+1]}-\sum_{l=0}^{k-1}(l+1)P_{\alpha [l+1]}g_{[k-l]}\Bigr],
\end{eqnarray}
$$

Elegimos $g=x$,
\begin{eqnarray}
P_{[0]} & = & 1,\\
P_{[k]} & = & \frac{1}{(k+1)g_{[0]}} \Bigl[\alpha(P_{[k]}-kP_{[k]}\Bigr] = \frac{(\alpha-k)(\alpha-(k-1))}{(k+1)k} P_{[k-1]} = \dots = \frac{\prod_{i=0}^{k-1}(\alpha - i)}{(k+1)!} P_{[0]} = \frac{1}{k!}\ ,
\end{eqnarray}

In [9]:
function expo(g,α,x0)
    P = zeros(g)
    P[1] = x0^(α)
    total = 0
    for k in 0:length(g)-2
        total = 0
        for l in 0:k-1
            total += α*((k-l+1)*P[l+1]*g[k-l+2])
            total -= (l+1)*P[l+2]*g[k-l+1]
        end
        total += α*P[k+1]*g[2]
        P[k+2] = total/((k+1)*g[1])
    end
    P
end

expo (generic function with 1 method)

In [10]:
expo([1//1,1//1,0,0,0],1//2,1//1)

5-element Array{Rational{Int64},1}:
  1//1  
  1//2  
 -1//8  
  1//16 
 -5//128

[Inspiración divina](https://www.sintef.no/globalassets/project/evitameeting/2010/ad2010.pdf) ya que al derivar dos veces obtenía un término con ${\rm d}g/{\rm d} x$ al cubo que era difícil de manejar.

La serie es

$$
S_{[k]} = \frac{1}{k} \sum_{l=0}^k l g_{[l]} C_{[k-l]},
$$
y
$$
C_{[k]} = -\frac{1}{k} \sum_{l=0}^k l g_{[l]} S_{[k-l]}.
$$

Al sustituir una en términos de la otra obtenemos, para el $\sin$:

$$
S_{[k]} = -\frac{1}{k} \sum_{l=0}^k l g_{[l]} \frac{1}{k-l}
\biggl(
 \sum_{l'=0}^{k-l} l' g_{[l']} S_{[k-l'-l]}
\biggr),
$$
mientras que para el $\cos$

$$
C_{[k]} = -\frac{1}{k} \sum_{l=0}^k l g_{[l]} \frac{1}{k-l}
\biggl(
 \sum_{l'=0}^{k-l} l' g_{[l']} C_{[k-l'-l]}
\biggr),
$$
con $C_{[0]} = \cos(x_0)$ y $S_{[0]} = \sin(x_0)$.

Por ejemplo, para $g(x) = x$ y $x_0 = 0$ tenemos que $g_{[l]} = \delta_{l,1}$ y $S_{[0]} = 0$ obtenemos

\begin{eqnarray}
S_{[0]} & = & 0,\\
E_{[k]} & = & -\frac{1}{k} \frac{1}{k-1}S_{[k-2]} = (-1)^2\frac{1}{k} \frac{1}{k-1}\frac{1}{k-2} \frac{1}{k-3}S_{[k-4]} = \dots \ ,
\end{eqnarray}
para $k=3$ y $k=5$ obtenemos los [términos correctos](http://www.wolframalpha.com/input/?i=taylor+sin(x) de la serie.

In [11]:
function seno(g)
    S = zeros(g)
    S[2] = 1.
    total = 0
    totalidad = 0
    for k in 2:length(g)-1 # el término de inicio es truculento ya que si ponemos 1 sobreescribe S[2] = 1.
        total = 0
        totalidad = 0
        for l in 1:k-1
            for lp in 1:k-l
                total += lp*g[lp+1]*S[k-lp-l+1]
            end
            totalidad += l*g[l+1]*total/(k-l)
        end
        S[k+1] = -totalidad/k
    end
    S
end

seno (generic function with 1 method)

In [12]:
seno([0,1//1,0,0,0,0])

6-element Array{Rational{Int64},1}:
  0//1  
  1//1  
  0//1  
 -1//6  
  0//1  
  1//120

In [13]:
function coseno(g)
    C = zeros(g)
    C[1] = 1.
    total = 0
    totalidad = 0
    for k in 1:length(g)-1
        total = 0
        totalidad = 0
        for l in 1:k-1
            for lp in 1:k-l
                total += lp*g[lp+1]*C[k-lp-l+1]
            end
            totalidad += l*g[l+1]*total/(k-l)
        end
        C[k+1] = -totalidad/k
    end
    C
end

coseno (generic function with 1 method)

In [14]:
coseno([0,1//1,0,0,0])

5-element Array{Rational{Int64},1}:
  1//1 
  0//1 
 -1//2 
  0//1 
  1//24