#  Tarea 2 | Amaro-Alcalá David

##  Ejercicio 1

Creamos diez datos aleatorios.

In [5]:
aleas = randn(10)

10-element Array{Float64,1}:
  1.46118  
 -0.408202 
  1.85224  
  0.0149698
  0.834022 
 -1.06282  
  0.593184 
 -1.05842  
  0.201673 
 -0.0780028

In [6]:
function histograma(nhist)
    # código
end

histograma (generic function with 1 method)

In [7]:
nhis = 3

3

Se juega con las funciones `max` y `min`.

In [8]:
max(aleas...)

1.8522360954131813

In [9]:
min(aleas...)

-1.0628249959445573

Definimos una cantidad que se usa después.

In [10]:
Δx = (max(aleas...) - min(aleas...))/nhis

0.9716870304525796

Quiero ver los intervalos.

In [11]:
a = min(aleas...)

for i in 1:nhis+1
    println(a)
    a += Δx
end

-1

Haciendo caso de la advertencia, tenemos que pensar la forma en la que poder tener que leer sólo una vez los datos. Esto es leemos un valor y aumentamos un "vector" en la entrada que corresponde al intervalo donde cae el valor.

In [12]:
a = min(aleas...)
res = zeros(nhis+1)
for i in 1:nhis+1
    if aleas[2] < a + Δx && aleas[2] >= a
        res[i] += 1
    end
    a += Δx
end

In [13]:
res

4-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0

Definimos la función `paso` que para un único valor, nos devuelve el vector con el valor que corresponde al intervalo en el que cae el valor, aumentado. En matemáticas: Si $\mathrm{valor} \in R_n$ entonces, $\mathrm{Vector}[R_n]++$.

In [14]:
"""
Función `paso`. Recibe __dos__ argumentos:

1. `valor`: Valor numérico que se va a buscar su lugar en algún intervalo.
2. `res`: Vector resultado de aumentar el valor que corresponde al intervalo en el que cae  `valor`.
"""

function paso(valor, res)
    a = min(aleas...)
    for i in 1:nhis+1
        if valor < a + Δx && valor >= a
            res[i] += 1
        end
        a += Δx
    end
    res
end

paso (generic function with 1 method)

In [15]:
?paso

Función `paso`. Recibe __dos__ argumentos:

1. `valor`: Valor numérico que se va a buscar su lugar en algún intervalo.
2. `res`: Vector resultado de aumentar el valor que corresponde al intervalo en el que cae  `valor`.


In [16]:
paso(aleas[2],zeros(nhis+1))

4-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0

In [17]:
"""
Función `completa` evalúa `paso` para cada uno de los valores en `listaValores`.
"""

function completo(listaValores)
    res = zeros(nhis + 1)
    for i in 1:length(listaValores)
        res = paso(listaValores[i], res)
    end
    res
end

completo (generic function with 1 method)

In [18]:
juas = completo(aleas)

4-element Array{Float64,1}:
 3.0
 5.0
 2.0
 0.0

In [19]:
min(aleas...) + Δx

-0.09113796549197761

In [20]:
min(aleas...) + 2Δx

0.880549064960602

In [21]:
min(aleas...) + 3Δx

1.8522360954131816

In [22]:
aleas

10-element Array{Float64,1}:
  1.46118  
 -0.408202 
  1.85224  
  0.0149698
  0.834022 
 -1.06282  
  0.593184 
 -1.05842  
  0.201673 
 -0.0780028

Vemos que sí funciona. Vamos a poner todo en una función.

Implementamos las funciones de arriba con mejores nombres y las usamos para generar el histograma.

In [23]:
function paso(valor, res, Δx,nhist,minimo)
    a = minimo
    for i in 1:nhist+1
        if valor <= a + Δx && valor >= a
            res[i] += 1
        end
        a += Δx
    end
    res
end

paso (generic function with 2 methods)

In [24]:
function completo(listaValores,nhist,Δx)
    res = zeros(nhist + 1)
    minimo = min(listaValores...)
    for i in 1:length(listaValores)
        res = paso(listaValores[i], res, Δx,nhist,minimo)
    end
    res
end

completo (generic function with 2 methods)

In [25]:
"""
`hiper` es la función que recibe el número de intervalos que deseamos tener.
Calcula `Δx` y se lo pasa a `completo`. 
"""

function hiper(nhist)
    aleas = randn(100)
    Δx = (max(aleas...) - min(aleas...))/nhist
    completo(aleas,nhist,Δx)
end

hiper (generic function with 1 method)

.0628249959445573
-0.09113796549197761
0.880549064960602
1.8522360954131818
search: paso parsefloat ParseError AbstractSparseVector PartialQuickSort parse



In [26]:
?hiper

search: 

`hiper` es la función que recibe el número de intervalos que deseamos tener. Calcula `Δx` y se lo pasa a `completo`. 


In [27]:
"""
`histograma` Recibe el número de intervalos. Utilizando a `hiper` recibe
el vector que tiene el histograma. Utiliza un ciclo `for` para generar
"visualmente" el histograma en su versión horizontal.
"""

function histograma(n)
    valores = hiper(n)
    for i in 1:length(valores)
        print(": ")
        for j in 1:valores[i]
            print("|")
        end
        println("")
    end
end

histograma (generic function with 1 method)

In [28]:
using PyPlot

INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/PyPlot.ji for module PyPlot.


hiper with_bigfloat_precision



INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/PyCall.ji for module PyCall.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/Conda.ji for module Conda.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/BinDeps.ji for module BinDeps.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/URIParser.ji for module URIParser.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/SHA.ji for module SHA.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/Colors.ji for module Colors.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/FixedPointNumbers.ji for module FixedPointNumbers.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/ColorTypes.ji for module ColorTypes.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/Reexport.ji for module Reexport.
INFO: Recompiling stale cache file /home/david/.julia/lib/v0.4/LaTeXStrings.ji for module LaTeXStrings.


LoadError: LoadError: InitError: Failed to pyimport("matplotlib"): PyPlot will not work until you have a functioning matplotlib module.

For automated Matplotlib installation, try configuring PyCall to use the Conda Python distribution within Julia.  Relaunch Julia and run:
      ENV["PYTHON"]=""
      Pkg.build("PyCall")
      using PyPlot

pyimport exception was: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError("No module named 'six'",)
  File "/usr/lib/python3.5/site-packages/matplotlib/__init__.py", line 124, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/usr/lib/python3.5/site-packages/matplotlib/rcsetup.py", line 34, in <module>
    from cycler import Cycler, cycler as ccycler
  File "/usr/lib/python3.5/site-packages/cycler.py", line 4, in <module>
    import six

during initialization of module PyPlot
while loading In[28], in expression starting on line 1

In [29]:
#writedlm("adf.txt", histograma(50))

###  Algunos ejemplitos

In [30]:
plt[:hist](randn(1000),50)

LoadError: LoadError: UndefVarError: plt not defined
while loading In[30], in expression starting on line 1

In [33]:
histograma(8)

: |
: ||
: |||||
: |||||||||||||||||||||||||
: |||||||||||||||||||||||||||||||
: ||||||||||||||||||
: ||||||||||||
: |||||
: |


In [32]:
plt[:hist](randn(100),8)

LoadError: LoadError: UndefVarError: plt not defined
while loading In[32], in expression starting on line 1

|||||
: ||||||||||||
: ||||||||||||||||||||
: |||||||||||||||||||||||||
: ||||||||||||||||||||||||
: ||||||||||
: ||
: 
: |
