# Tarea 2 --- Amaro-Alcalá David

# Razonamiento
Me pareció correcta la idea de tomar el valor de mayor complejidad como el tipo de dato que fuera el que devolviera la función, _i.e._, si le metemos a la función un real y dos enteros que tomara el entero como el valor a devolver (cuando la solución fuera real), así que el primer paso era conocer este tipo. Para hacerlo primero se me ocurrio aplicar `typeof` a cada elemento de la lista y de alguna manera conocerlo. Afortunadamente al utilizar la función `map` y meter en una lista los coeficientes esta devolvía por igual el valor del término de mayor complejidad.

Por lo que sólo basta calcular la raíz y convertirlo al tipo encontrado. Esto hubiera sido sencillo si no fuera porque `convert` no convierte `Complex{Float64}` a otro que no sea el mismo, ni siquiera `Complex{Int64}`, como se puede observar en el primer ejemplo.

In [1]:
?map

search: 

```
map(f, c...) -> collection
```

Transform collection `c` by applying `f` to each element. For multiple collection arguments, apply `f` elementwise.

```jldoctest
julia> map((x) -> x * 2, [1, 2, 3])
3-element Array{Int64,1}:
 2
 4
 6

julia> map(+, [1, 2, 3], [10, 20, 30])
3-element Array{Int64,1}:
 11
 22
 33
```


In [2]:
map(typeof,[1,1.,1+im])

map map! mapfoldr mapfoldl mapslices mapreduce mapreducedim pmap mmap



3-element Array{DataType,1}:
 Complex{Float64}
 Complex{Float64}
 Complex{Float64}

In [3]:
function raiz1(a,b,c)
    valor = tipo(a,b,c)
    Any[convert(valor,(-b+sqrt(complex(b^2-4*a*c)))/2a),
        convert(valor,(-b-sqrt(complex(b^2-4*a*c)))/2a)]
end

function tipo(a,b,c)
    tipos = map(typeof,[a,b,c])
    tipos[1]
end

function identificador(raiz)
    if isreal(raiz)
        if isinteger(raiz)
            return round(Int,real(raiz))
        end
        return real(raiz)
    else
        return raiz
    end
end

identificador (generic function with 1 method)

In [4]:
raiz1(1,3,33)

LoadError: LoadError: InexactError()
while loading In[4], in expression starting on line 1

In [5]:
raiz1(1.+0.im,3.+0.im,33.+0.im)

2-element Array{Any,1}:
 -1.5+5.54527im
 -1.5-5.54527im

In [6]:
raiz1(1.+0im,3.+0im,33.+0im)

LoadError: LoadError: InexactError()
while loading In[6], in expression starting on line 1

In [7]:
convert(Complex{Float64},-1.5 + 5.545268253204709im)

-1.5 + 5.545268253204709im

In [8]:
raiz1(1,4,3.3)

2-element Array{Any,1}:
 -1.16334
 -2.83666

In [9]:
raiz1(1,4,3.3)

2-element Array{Any,1}:
 -1.16334
 -2.83666

In [10]:
raiz1(1,4,4)

2-element Array{Any,1}:
 -2
 -2